version: "3"
services:
  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=password
      
  web:
    build: .
    environment: 
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on: 
      - db
