version: 2.1

orbs:
  ruby: circleci/ruby@1.1.4 #bundleをinstallするため
  node: circleci/node@4.5.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.6-node
    steps:
      - checkout
      - ruby/install-deps:
          key: v2-gem-cache
      - node/install-packages:
          pkg-manager: yarn
          cache-path: "yarn.lock"
  test:
    docker:
      - image: cimg/ruby:2.6.6-node
      - image: circleci/postgres:12.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: "password"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: "password"
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps:
          key: v2-gem-cache
      - node/install-packages:
          pkg-manager: yarn
          cache-path: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Masterkey setup
          command: echo $RAILS_MASTER_KEY > ~/project/config/master.key
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Webpack build
          command: bundle exec rails webpacker:compile
      - run:
          name: App test
          command: bundle exec rails test
  deploy:
    docker:
      - image: cimg/ruby:2.6.6-node
    steps:
      - checkout
      - ruby/install-deps:
          key: v2-gem-cache
      - run:
          name: Masterkey setup
          command: echo $RAILS_MASTER_KEY > ~/project/config/master.key
      - add_ssh_keys:
          fingerprints:
            - "24:15:e9:da:51:27:16:28:97:ca:66:aa:f4:c1:7a:f0"
      - run:
          name: App deploy
          command: bundle exec cap production deploy


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
